name: Torrent Cleaner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: python/t_cleaner
    
    - name: Check formatting with Black
      run: black --check .
      working-directory: python/t_cleaner

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s tests
        coverage report
        coverage xml
      working-directory: python/t_cleaner

    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Only needed for private repos
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
